# Generated by Django 4.1.7 on 2023-03-01 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('post', 'post'), ('like', 'like'), ('comment', 'comment'), ('follow', 'follow')], default='post', max_length=7)),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_outbox', to='app.author')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_inbox', to='app.author')),
            ],
        ),
    ]
