# Generated by Django 4.1.7 on 2023-03-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=320),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(null=True),
        ),
    ]
