# Generated by Django 4.1.7 on 2023-03-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_foreignapinodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignapinodes',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foreignapinodes',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
