# Generated by Django 4.1.7 on 2023-03-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_foreignapinodes'),
        ('app', '0026_alter_author_url'),
    ]

    operations = [
    ]
