# Generated by Django 4.1.7 on 2023-03-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_merge_0023_foreignapinodes_0026_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='private_posts', to='app.author'),
        ),
    ]
