# Generated by Django 4.1.7 on 2023-03-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_post_title'),
        ('app', '0028_alter_post_receivers'),
    ]

    operations = [
    ]
