# Generated by Django 4.1.7 on 2023-03-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_0025_alter_post_title_0028_alter_post_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
