# Generated by Django 4.1.7 on 2023-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
