# Generated by Django 4.1.7 on 2023-03-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_comment_contenttype_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contentType',
        ),
    ]
