# Generated by Django 4.1.7 on 2023-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_comment_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
