# Generated by Django 4.1.7 on 2023-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
