# Generated by Django 4.1.7 on 2023-04-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_author_github'),
        ('app', '0039_alter_post_content_type'),
    ]

    operations = [
    ]
